# Generated by Django 3.2.6 on 2021-11-05 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reservaSala',
            fields=[
                ('usuario_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin')),
                ('backgroundColor', models.CharField(default='#f39c12', max_length=50, verbose_name='Color de fondo')),
                ('borderColor', models.CharField(default='#f39c12', max_length=50, verbose_name='Color de borde')),
                ('allDay', models.BooleanField(blank=True, default=False)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
