# Generated by Django 3.2.6 on 2021-11-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservarsala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasala',
            name='hora_inicio',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
