# Generated by Django 3.2.6 on 2021-11-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservarsala', '0002_reservasala_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservasala',
            name='hora_inicio',
        ),
    ]
