# Generated by Django 3.2.6 on 2021-11-05 19:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservarsala', '0003_remove_reservasala_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasala',
            name='autor',
            field=models.IntegerField(blank=True, default=django.contrib.auth.models.User, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
