# Generated by Django 3.2.6 on 2021-11-05 19:17

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservarsala', '0004_alter_reservasala_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasala',
            name='autor',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
