# Generated by Django 3.2.6 on 2021-11-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservarsala', '0005_alter_reservasala_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservasala',
            old_name='autor',
            new_name='creador',
        ),
    ]
