# Generated by Django 3.2.6 on 2021-11-05 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservarsala', '0006_rename_autor_reservasala_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasala',
            name='creador',
            field=models.ForeignKey(blank=True, db_column='autor_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
