# Generated by Django 3.2.6 on 2021-12-16 13:43

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservarsala', '0007_alter_reservasala_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasala',
            name='creador',
            field=models.ForeignKey(blank=True, db_column='autor_id', default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
