# Generated by Django 3.2.6 on 2022-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoMovimientosWms',
            fields=[
                ('nro_tarea', models.IntegerField(blank=True, db_column='NRO_TAREA', null=True)),
                ('nro_movim', models.IntegerField(db_column='NRO_MOVIM', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='FECHA', null=True)),
                ('hora', models.CharField(blank=True, db_column='HORA', max_length=5, null=True)),
                ('cod_articulo', models.CharField(db_column='COD_ARTICULO', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=250, null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='CANTIDAD', null=True)),
                ('tipo_movimiento', models.CharField(blank=True, db_column='TIPO_MOVIMIENTO', max_length=100, null=True)),
                ('ubic_origen', models.CharField(blank=True, db_column='UBIC_ORIGEN', max_length=10, null=True)),
                ('depo_origen', models.CharField(blank=True, db_column='DEPO_ORIGEN', max_length=50, null=True)),
                ('ubic_destino', models.CharField(db_column='UBIC_DESTINO', max_length=10)),
                ('depo_destino', models.CharField(blank=True, db_column='DEPO_DESTINO', max_length=50, null=True)),
                ('usuario', models.CharField(db_column='USUARIO', max_length=256)),
            ],
            options={
                'db_table': 'RO_MOVIMIENTOS_WMS',
                'managed': False,
            },
        ),
    ]
