# Generated by Django 3.2.6 on 2022-06-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoMovimientosWms',
            fields=[
                ('nro_tarea', models.IntegerField(blank=True, db_column='NRO_TAREA', null=True)),
                ('nro_movim', models.IntegerField(db_column='NRO_MOVIM', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='FECHA', null=True)),
                ('hora', models.CharField(blank=True, db_column='HORA', max_length=5, null=True)),
                ('cod_articulo', models.CharField(db_column='COD_ARTICULO', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=250, null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='CANTIDAD', null=True)),
                ('tipo_movimiento', models.CharField(blank=True, db_column='TIPO_MOVIMIENTO', max_length=100, null=True)),
                ('ubic_origen', models.CharField(blank=True, db_column='UBIC_ORIGEN', max_length=10, null=True)),
                ('depo_origen', models.CharField(blank=True, db_column='DEPO_ORIGEN', max_length=50, null=True)),
                ('ubic_destino', models.CharField(db_column='UBIC_DESTINO', max_length=10)),
                ('depo_destino', models.CharField(blank=True, db_column='DEPO_DESTINO', max_length=50, null=True)),
                ('usuario', models.CharField(db_column='USUARIO', max_length=256)),
            ],
            options={
                'db_table': 'RO_MOVIMIENTOS_WMS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(db_column='id_Ubicacion', primary_key=True, serialize=False)),
                ('cod_ubicacion', models.CharField(db_column='Cod_Ubicacion', max_length=10)),
                ('nombre_ubicacion', models.CharField(blank=True, db_column='Nombre_Ubicacion', max_length=50, null=True)),
                ('tipo_ubicacion', models.CharField(blank=True, db_column='Tipo_Ubicacion', max_length=50, null=True)),
                ('num_deposito', models.CharField(blank=True, db_column='Num_Deposito', max_length=50, null=True)),
                ('estado', models.BooleanField(db_column='Estado')),
                ('estado_u', models.CharField(blank=True, db_column='Estado_U', max_length=4, null=True)),
                ('rack', models.IntegerField(blank=True, db_column='Rack', null=True)),
                ('modulo', models.IntegerField(blank=True, db_column='Modulo', null=True)),
                ('altura', models.IntegerField(blank=True, db_column='Altura', null=True)),
                ('anc_rubro', models.TextField(blank=True, db_column='Anc_Rubro', null=True)),
                ('anc_destino', models.TextField(blank=True, db_column='Anc_Destino', null=True)),
                ('anc_linea', models.TextField(blank=True, db_column='Anc_Linea', null=True)),
                ('anc_temporada', models.TextField(blank=True, db_column='Anc_Temporada', null=True)),
                ('anc_categoria', models.TextField(blank=True, db_column='Anc_Categoria', null=True)),
            ],
            options={
                'db_table': 'Ubicacion',
                'managed': True,
            },
        ),
    ]
