# Generated by Django 3.2.6 on 2022-09-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccionario',
            fields=[
                ('nro_sucursal', models.IntegerField(db_column='NRO_SUCURSAL', primary_key=True, serialize=False)),
                ('cod_client', models.CharField(db_column='COD_CLIENT', max_length=8)),
                ('desc_sucursal', models.CharField(db_column='DESC_SUCURSAL', max_length=50)),
                ('canal', models.CharField(blank=True, db_column='CANAL', max_length=15, null=True)),
                ('tipo_local', models.CharField(blank=True, db_column='TIPO_LOCAL', max_length=30, null=True)),
                ('grupo_empresario', models.CharField(db_column='GRUPO_EMPRESARIO', max_length=60)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=60)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=50)),
                ('tango', models.CharField(db_column='TANGO', max_length=2)),
                ('base_nombre', models.CharField(blank=True, db_column='BASE_NOMBRE', max_length=50, null=True)),
                ('conexion_dns', models.CharField(blank=True, db_column='CONEXION_DNS', max_length=50, null=True)),
                ('tienda', models.CharField(db_column='TIENDA', max_length=2)),
            ],
            options={
                'db_table': 'DIRECCIONARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SucursalesLakers',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nro_sucursal', models.IntegerField(db_column='NRO_SUCURSAL')),
                ('cod_client', models.CharField(db_column='COD_CLIENT', max_length=8)),
                ('desc_sucursal', models.CharField(db_column='DESC_SUCURSAL', max_length=50)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=60)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=50)),
                ('localidad', models.CharField(db_column='LOCALIDAD', max_length=50)),
                ('provincia', models.CharField(db_column='PROVINCIA', max_length=50)),
                ('canal', models.CharField(blank=True, db_column='CANAL', max_length=15, null=True)),
                ('habilitado', models.BooleanField(blank=True, db_column='HABILITADO', null=True)),
                ('dashboard_bi', models.BooleanField(blank=True, db_column='DASHBOARD_BI', null=True)),
                ('tango', models.BooleanField(blank=True, db_column='TANGO', null=True)),
                ('suc_madre', models.BooleanField(blank=True, db_column='SUC_MADRE', null=True)),
                ('nro_suc_madre', models.IntegerField(blank=True, db_column='NRO_SUC_MADRE', null=True)),
                ('tipo_local', models.CharField(blank=True, db_column='TIPO_LOCAL', max_length=30, null=True)),
                ('integracion_mercadopago_madre', models.BooleanField(blank=True, db_column='INTEGRACION_MERCADOPAGO_MADRE', null=True)),
                ('integracion_mercadopago_hija', models.BooleanField(blank=True, db_column='INTEGRACION_MERCADOPAGO_HIJA', null=True)),
                ('empresa_ferreteria', models.BooleanField(blank=True, db_column='EMPRESA_FERRETERIA', null=True)),
                ('conexion_dns', models.CharField(blank=True, db_column='CONEXION_DNS', max_length=50, null=True)),
                ('usuario_dns', models.CharField(blank=True, db_column='USUARIO_DNS', max_length=30, null=True)),
                ('clave_dns', models.CharField(blank=True, db_column='CLAVE_DNS', max_length=30, null=True)),
                ('conexion_teamviewer_madre', models.CharField(blank=True, db_column='CONEXION_TEAMVIEWER_MADRE', max_length=30, null=True)),
                ('clave_teamviewer', models.CharField(blank=True, db_column='CLAVE_TEAMVIEWER', max_length=30, null=True)),
                ('factura_elect', models.BooleanField(blank=True, db_column='FACTURA_ELECT', null=True)),
                ('lapos_integrado', models.BooleanField(blank=True, db_column='LAPOS_INTEGRADO', null=True)),
                ('link_pedido', models.CharField(blank=True, db_column='LINK_PEDIDO', max_length=50, null=True)),
                ('link_sales', models.CharField(blank=True, db_column='LINK_SALES', max_length=50, null=True)),
                ('lapos_modelo', models.CharField(blank=True, db_column='LAPOS_MODELO', max_length=30, null=True)),
                ('version_soft_lapos', models.CharField(blank=True, db_column='VERSION_SOFT_LAPOS', max_length=30, null=True)),
                ('cable_lapos_integrado', models.CharField(blank=True, db_column='CABLE_LAPOS_INTEGRADO', max_length=30, null=True)),
                ('n_llave_tango', models.CharField(blank=True, db_column='N_LLAVE_TANGO', max_length=20, null=True)),
                ('llave_prueba', models.BinaryField(blank=True, db_column='LLAVE_PRUEBA', max_length='max', null=True)),
                ('base_nombre', models.CharField(blank=True, db_column='BASE_NOMBRE', max_length=50, null=True)),
                ('conexion_teamviewer_hija', models.CharField(blank=True, db_column='CONEXION_TEAMVIEWER_HIJA', max_length=30, null=True)),
                ('usuario_pc_madre', models.CharField(blank=True, db_column='USUARIO_PC_MADRE', max_length=30, null=True)),
                ('clave_usuario_m', models.BinaryField(blank=True, db_column='CLAVE_USUARIO_M', max_length='max', null=True)),
                ('cod_deposi', models.CharField(blank=True, db_column='COD_DEPOSI', max_length=2, null=True)),
                ('mail', models.CharField(blank=True, db_column='MAIL', max_length=50, null=True)),
                ('fecha_cierre', models.DateField(blank=True, db_column='FECHA_CIERRE', null=True)),
            ],
            options={
                'db_table': 'SUCURSALES_LAKERS',
                'managed': True,
            },
        ),
    ]
