# Generated by Django 3.2.6 on 2022-10-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasLakersBis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccionario',
            options={'managed': False, 'ordering': ['nro_sucursal']},
        ),
        migrations.AddField(
            model_name='sucursaleslakers',
            name='horario',
            field=models.CharField(blank=True, db_column='HORARIO', max_length=20, null=True),
        ),
    ]
