# Generated by Django 3.2.6 on 2023-04-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasLakersBis', '0002_auto_20221025_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursaleslakers',
            name='integra_vtex',
            field=models.BooleanField(blank=True, db_column='INTEGRA_VTEX', null=True),
        ),
    ]
