# Generated by Django 3.2.6 on 2024-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasLakersBis', '0003_sucursaleslakers_integra_vtex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SofStockLakers',
            fields=[
                ('articulo', models.CharField(db_column='ARTICULO', max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=30, null=True)),
                ('nro_sucursal', models.IntegerField(db_column='NRO_SUCURSAL')),
                ('cod_client', models.CharField(db_column='COD_CLIENT', max_length=8)),
                ('desc_sucursal', models.CharField(db_column='DESC_SUCURSAL', max_length=50)),
                ('cod_deposi', models.CharField(db_column='COD_DEPOSI', max_length=3)),
                ('cant_stock', models.FloatField(blank=True, db_column='CANT_STOCK', null=True)),
                ('rubro', models.CharField(blank=True, db_column='RUBRO', max_length=40, null=True)),
                ('categoria', models.CharField(db_column='CATEGORIA', max_length=50)),
                ('temporada', models.CharField(db_column='TEMPORADA', max_length=20)),
                ('destino', models.CharField(db_column='DESTINO', max_length=20)),
                ('precio', models.FloatField(blank=True, db_column='PRECIO', null=True)),
            ],
            options={
                'db_table': 'SOF_STOCK_LAKERS',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='sucursaleslakers',
            name='nro_sucursal',
            field=models.IntegerField(db_column='NRO_SUCURSAL', error_messages={'unique': 'La sucursal ya existe.'}, unique=True),
        ),
    ]
