# Generated by Django 3.2.6 on 2024-07-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasLakersBis', '0004_auto_20240425_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursaleslakers',
            name='horario',
            field=models.CharField(blank=True, db_column='HORARIO', max_length=50, null=True),
        ),
    ]
