# Generated by Django 3.2.6 on 2021-12-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('COD_TRANSP', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('NOMBRE_TRA', models.CharField(max_length=100)),
                ('COSTE_BULTO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('COSTE_SEGURO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('COSTE_RETIRO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('COSTE_ENTREGA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RETIRA_EN_CD', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
