# Generated by Django 3.2.6 on 2021-12-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='OBSERVASIONES',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
