# Generated by Django 3.2.6 on 2021-12-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0002_transporte_observasiones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='NOMBRE_TRA',
        ),
        migrations.AddField(
            model_name='transporte',
            name='NOMBRE',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
