# Generated by Django 3.2.6 on 2022-04-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCentral',
            fields=[
                ('articulo', models.CharField(db_column='COD_ARTICU', max_length=15)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=30, null=True)),
                ('deposito', models.CharField(db_column='COD_DEPOSI', max_length=2)),
                ('total', models.FloatField(blank=True, db_column='STOCK_TOTAL', null=True)),
                ('comp', models.FloatField(blank=True, db_column='CANT_COMP', null=True)),
                ('reserva', models.IntegerField(db_column='CANT_RESERVA')),
                ('excluido', models.IntegerField(db_column='STOCK_EXCLUIDO')),
                ('disponible', models.FloatField(db_column='STOCK_DISPONIBLE')),
                ('destino', models.CharField(blank=True, db_column='DESTINO', max_length=20, null=True)),
                ('rubro', models.CharField(blank=True, db_column='RUBRO', max_length=40, null=True)),
                ('categoria', models.CharField(blank=True, db_column='CATEGORIA', max_length=50, null=True)),
                ('temporada', models.CharField(blank=True, db_column='TEMPORADA', max_length=20, null=True)),
                ('color', models.CharField(blank=True, db_column='COLOR', max_length=10, null=True)),
            ],
            options={
                'db_table': 'STOCK_CENTRAL',
                'managed': False,
            },
        ),
    ]
