# Generated by Django 3.2.6 on 2022-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasTango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SjStockDisponibleEcommerce',
            fields=[
                ('articulo', models.CharField(db_column='COD_ARTICU', max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=30, null=True)),
                ('deposito', models.CharField(db_column='COD_DEPOSI', max_length=2)),
                ('total', models.DecimalField(blank=True, db_column='STOCK', decimal_places=7, max_digits=22, null=True)),
                ('stock_seguridad', models.DecimalField(db_column='STOCK_SEGURIDAD', decimal_places=7, max_digits=22)),
                ('cant_comp', models.DecimalField(db_column='CANT_COMP', decimal_places=7, max_digits=22)),
                ('reserva_ecommerce', models.IntegerField(db_column='RESERVA_ECOMMERCE')),
                ('stock_reserva_vtex', models.DecimalField(db_column='STOCK_RESERVA_VTEX', decimal_places=7, max_digits=23)),
                ('stock_excluido', models.IntegerField(db_column='STOCK_EXCLUIDO')),
                ('stock_disponible', models.DecimalField(blank=True, db_column='STOCK_DISPONIBLE', decimal_places=7, max_digits=26, null=True)),
                ('rubro', models.CharField(blank=True, db_column='RUBRO', max_length=40, null=True)),
            ],
            options={
                'db_table': 'SJ_STOCK_DISPONIBLE_ECOMMERCE',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='stockcentral',
            table='STOCK_CENTRAL_EDU',
        ),
    ]
