# Generated by Django 3.2.6 on 2023-04-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasTango', '0002_auto_20220420_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosError',
            fields=[
                ('CodigoError', models.IntegerField(primary_key=True, serialize=False)),
                ('DescripcionError', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('IdTurno', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoProveedor', models.IntegerField()),
                ('FechaAsignacion', models.DateTimeField()),
                ('OrdenCompra', models.CharField(max_length=14)),
                ('Remitos', models.CharField(max_length=100)),
                ('CantidadUnidades', models.IntegerField()),
                ('CantidadBultos', models.IntegerField(blank=True, null=True)),
                ('Recepcionado', models.BooleanField(default=False)),
                ('Auditado', models.BooleanField(default=False)),
                ('Posicionado', models.BooleanField(default=False)),
                ('Observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('CodigoError', models.IntegerField(blank=True, null=True)),
                ('RecepcionadoFechaHora', models.DateTimeField(blank=True, null=True)),
                ('AuditadoFechaHora', models.DateTimeField(blank=True, null=True)),
                ('PosicionadoFechaHora', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
