# Generated by Django 3.2.6 on 2024-04-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultasTango', '0004_alter_turno_codigoproveedor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockcentral',
            table='STOCK_CENTRAL',
        ),
    ]
