# Generated by Django 3.2.6 on 2024-05-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasTango', '0005_alter_stockcentral_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EB_facturaManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateTimeField()),
                ('numeroSucursal', models.IntegerField()),
                ('tipoFactura', models.IntegerField(choices=[('0', 'Factura-A'), ('1', 'Factura-B')])),
                ('numeroFact_A', models.IntegerField()),
                ('imgFact_A', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
