# Generated by Django 3.2.6 on 2024-05-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultasTango', '0007_auto_20240512_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eb_facturamanual',
            old_name='imgFacturo',
            new_name='imgFactura',
        ),
    ]
