# Generated by Django 3.2.6 on 2024-07-01 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasTango', '0009_auto_20240515_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eb_facturamanual',
            name='numeroFactura',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El formato debe ser XXXXX-XXXXXXX', regex='^\\d{5}-\\d{8}$')]),
        ),
    ]
